version: "3.9"

services:
  user_service:  
    build: 
      context: ./user_service
      dockerfile: Dockerfile
    container_name: user_service
    volumes:
      - ./user_service:/app
    working_dir: /app
    ports:
      - "8000:8000"   
    env_file:
    - user_service/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  post_service:
    build:
      context: ./post_service
      dockerfile: Dockerfile
    container_name: post_service
    volumes:
      - ./post_service:/app
    working_dir: /app
    env_file:
     - post_service/.env
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload