version: "3.9"

services:
  user_service:  
    image: user_service:latest
    ports:
      - "8000:8000"   
    env_file:
    - user_service/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  post_service:
    image: post_service:latest
    env_file:
     - post_service/.env
    ports:
      - "8001:8001"
    command: uvicorn main:app --host 0.0.0.0 --port 8001