"""Add unique_hash to posts

Revision ID: 9afe65199017
Revises: 37731683ee02
Create Date: 2025-08-17 14:28:26.480126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9afe65199017'
down_revision: Union[str, None] = '37731683ee02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('unique_hash', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'posts', ['unique_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='unique')
    op.drop_column('posts', 'unique_hash')
    # ### end Alembic commands ###
